language: cpp
os: linux
sudo: false
dist: trusty

env:
  global:
  - DEVKITPRO=/opt/devkitpro
  - DEVKITA64=/opt/devkitpro/devkitA64

cache:
  directories:
  - "$HOME/.local"
  - "$DEVKITPRO"

addons:
  apt:
    packages:
    - p7zip-full

before_install:
- mkdir -p "${DEVKITPRO}"
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget https://github.com/devkitPro/pacman/releases/download/devkitpro-pacman-1.0.1/devkitpro-pacman.deb
  -O /tmp/devkitpro-pacman.deb; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo dpkg -i /tmp/devkitpro-pacman.deb;
  fi
- yes | sudo dkp-pacman -Syu devkitA64 --needed
- yes | sudo dkp-pacman -Syu general-tools --needed
- yes | sudo dkp-pacman -Syu switch-tools --needed
- yes | sudo dkp-pacman -Syu libnx --needed

before_script:
- cd $TRAVIS_BUILD_DIR/

script:
- git clone https://github.com/Thog/nx-dreport nx-dreport
- "(cd nx-dreport && make)"

before_deploy:
- cd $TRAVIS_BUILD_DIR/
- mkdir -p "copy-to-sd"
- commit="$(git rev-parse --short=7 HEAD)"
- (cp nx-dreport/nx-dreport.kip copy-to-sd/nx-dreport.kip1)
- zip -r sdfiles_$commit.zip copy-to-sd

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: kJnxj6VMVDdSH40n/B+6u0VetEi9ThsEoWxWHxCLdl99Rolcb14kMgZRfr35cc9/tvFCij//aHBkFx/JbnpJMHvD0lKDEMc90aJn/RIwveduVcJbJqHXEjWgemnmlkMYAp3Elwz2QYCils3H31LqXYACkvzYj8vkN0scoDIDokPj7BckF7UoLlEkIjgsqG2IbjUradpFOUPAiUPeVgEt1/CihesADwBQlbaJVjAV5g5t8MNvm3IRdpL+aPoO17BGQKbI3/WJ32vNrO04L2x9V2C5zGD+tl3Tux8NRt/jVQTKDWOqOgFcEsG084Z6j+c3RBCv2eOow043fxFEnu2isr38C7jxLCp5zUEGAusvUB/xrJjpr6j2cmtfTmEizxq055/tFBwsLsE6Zio7dTBIiU7j2XX2ZD2SDcDNbwxUq4XTWh7Awd5eK9xnjkx/ez3Q2cYyAKwfotb9GNR0Kesiy21PJmFmzAZ7eJF/TZhPk3mdEBFaDDYn+CR1WTKwl1P967DlCTCiEADQiyVkBxoDujV3sMCzNy7liFbUX5XDJqKFXEPjSW8GlCKU5xgO09ziVyH7J0rT0MSDD9LCt8gbFULZCkxciFpSINnKLojqCkySHKJ08R2XKlR4wP7J4iaOTSon8SD+c2dM76xO1K+5sWXyLViz5QoAevXv3qwAj5w=
  file: sdfiles_$commit.zip
  name: SDFiles $commit
  body: SDFiles.zip Update
  on:
    repo: Brawl345/Switch-SDFiles-Autobuilder
