language: cpp
os: linux
sudo: false
dist: trusty

env:
  global:
  - DEVKITPRO=/opt/devkitpro
  - DEVKITA64=/opt/devkitpro/devkitA64
  - DEVKITARM=/opt/devkitpro/devkitARM

cache:
  directories:
  - "$HOME/.local"
  - "$DEVKITPRO"

addons:
  apt:
    packages:
    - p7zip-full

before_install:
- mkdir -p "${DEVKITPRO}"
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget https://github.com/devkitPro/pacman/releases/download/devkitpro-pacman-1.0.1/devkitpro-pacman.deb
  -O /tmp/devkitpro-pacman.deb; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo dpkg -i /tmp/devkitpro-pacman.deb;
  fi
- yes | sudo dkp-pacman -Syu devkitA64 --needed
- yes | sudo dkp-pacman -Syu devkitARM --needed
- yes | sudo dkp-pacman -Syu general-tools --needed
- yes | sudo dkp-pacman -Syu switch-tools --needed
- yes | sudo dkp-pacman -Syu libnx --needed
- yes | sudo dkp-pacman -Syu switch-zlib --needed
- yes | sudo dkp-pacman -Syu switch-freetype --needed

before_script:
- cd $TRAVIS_BUILD_DIR/

script:
- git clone https://github.com/Atmosphere-NX/Atmosphere Atmosphere
- cd Atmosphere && ATMOSPHERE_VER=$(git rev-parse --short HEAD) && git apply ../remove_exosphere_dependency.patch
- "(cd stratosphere/libstratosphere && make)"
- "(cd stratosphere/loader && make)"
- "(cd stratosphere/sm && make)"
- git clone https://github.com/CTCaer/hekate hekate
- cd hekate && HEKATE_VER=$(git describe --tags $(git rev-list --tags --max-count=1)) && git checkout $HEKATE_VER && make && cd ..
- git clone https://github.com/Thog/nx-dreport nx-dreport
- cd nx-dreport && DREPORT_VER=$(git rev-parse --short HEAD) && make && cd ..
- git clone https://github.com/Adubbz/Gag-Order Gag-Order
- cd Gag-Order && GAG_VER=$(git describe --tags $(git rev-list --tags --max-count=1)) && git checkout $GAG_VER && make && cd ..
- git clone https://github.com/StevenMattera/nx-hbmenu nx-hbmenu
- cd nx-hbmenu && HBMENU_VER=$(git rev-parse --short HEAD) && make nx && cd ..
- git clone https://github.com/switchbrew/nx-hbloader nx-hbloader
- cd nx-hbloader && HBLOADER_VER=$(git rev-parse --short HEAD) && make && cd ..

before_deploy:
- cd $TRAVIS_BUILD_DIR/
- mkdir -p "workdir"
- mkdir -p "workdir/copy-to-sd"
- mkdir -p "workdir/copy-to-sd/switch"
- mkdir -p "workdir/copy-to-sd/atmosphere/titles/010000000000100D/exefs"
- echo -e "Hekate All-in-One Package\n\nIncluded:">README.txt
- echo -e "* Hekate CTCaer Mod $HEKATE_VER">>README.txt
- cp hekate/ipl.bin workdir/hekate_ctcaer_$HEKATE_VER.bin
- cp hekate_ipl.ini workdir/copy-to-sd/
- echo -e "* Using parts of Atmosphère $ATMOSPHERE_VER (removed Exosphere API check)">>README.txt
- cp Atmosphere/stratosphere/loader/loader.kip workdir/copy-to-sd/loader.kip1
- cp Atmosphere/stratosphere/sm/sm.kip workdir/copy-to-sd/sm.kip1
- echo -e "* NX-dreport $DREPORT_VER">>README.txt
- cp nx-dreport/nx-dreport.kip workdir/copy-to-sd/
- echo -e "* Gag-Order $GAG_VER">>README.txt
- cp Gag-Order/Gag-Order.nro workdir/copy-to-sd/switch/
- echo -e "* StevenMattera's Homebrew Menu Fork $HBMENU_VER">>README.txt
- cp nx-hbmenu/nx-hbmenu.nro workdir/copy-to-sd/hbmenu.nro
- echo -e "* Homebrew Loader $HBLOADER_VER">>README.txt
- cp nx-hbloader/hbl.npdm workdir/copy-to-sd/atmosphere/titles/010000000000100D/exefs/main.npdm
- cp nx-hbloader/hbl.nso workdir/copy-to-sd/atmosphere/titles/010000000000100D/exefs/main
- touch workdir/copy-to-sd/atmosphere/titles/010000000000100D/exefs/rtld.stub
- cp README.txt workdir/
- cd "workdir"
- zip -r sdfiles.zip .

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: kJnxj6VMVDdSH40n/B+6u0VetEi9ThsEoWxWHxCLdl99Rolcb14kMgZRfr35cc9/tvFCij//aHBkFx/JbnpJMHvD0lKDEMc90aJn/RIwveduVcJbJqHXEjWgemnmlkMYAp3Elwz2QYCils3H31LqXYACkvzYj8vkN0scoDIDokPj7BckF7UoLlEkIjgsqG2IbjUradpFOUPAiUPeVgEt1/CihesADwBQlbaJVjAV5g5t8MNvm3IRdpL+aPoO17BGQKbI3/WJ32vNrO04L2x9V2C5zGD+tl3Tux8NRt/jVQTKDWOqOgFcEsG084Z6j+c3RBCv2eOow043fxFEnu2isr38C7jxLCp5zUEGAusvUB/xrJjpr6j2cmtfTmEizxq055/tFBwsLsE6Zio7dTBIiU7j2XX2ZD2SDcDNbwxUq4XTWh7Awd5eK9xnjkx/ez3Q2cYyAKwfotb9GNR0Kesiy21PJmFmzAZ7eJF/TZhPk3mdEBFaDDYn+CR1WTKwl1P967DlCTCiEADQiyVkBxoDujV3sMCzNy7liFbUX5XDJqKFXEPjSW8GlCKU5xgO09ziVyH7J0rT0MSDD9LCt8gbFULZCkxciFpSINnKLojqCkySHKJ08R2XKlR4wP7J4iaOTSon8SD+c2dM76xO1K+5sWXyLViz5QoAevXv3qwAj5w=
  file: sdfiles.zip
  name: SDFiles $(date +'%d.%m.%Y %R') UTC
  body: SDFiles.zip Update
  on:
    repo: Brawl345/Switch-SDFiles-Autobuilder
